### ISSUE TITLE
Optimize form fields for iPhone

### ISSUE THREAD

**Issue by simevidas** [justmarkup/demos#2]
Then testing the demos for https://justmarkup.com/log/2016/10/enhancing-a-comment-form/ on an iPhone, the browser zooms in whenever I tap on one of the inputs. I _think_ this is due to the `font-size` being too small. This is a problem because the browser leaves the page in a zoomed-in state even after the user has finished editing the field (so the user has to repeatedly pinch-to-zoom to see the whole page again). It might be worth trying to use larger font sizes for the form fields (or making them narrower, not sure).

**Comment by justmarkup** [comment]
Thanks a lot. I changed the font-size to 16px which seems to be the minimum size to prevent auto zoom on iOS.
