### ISSUE TITLE
Chrome extensions aimed at textarea can spoil the form

### ISSUE THREAD

**Issue by zawsx** [justmarkup/demos#4]
I'm using Grammarly for text entry but I guess this could happen with any extension that targets form entry.  With your demo, after submit, I get white text on a white background
Is it maybe possible to override an extension's interference because, if not, we might as well give up...

![image](https://cloud.githubusercontent.com/assets/6049993/23019003/43731812-f438-11e6-9f5a-abd65d393f05.png)

**Comment by justmarkup** [comment]
Hi @zawsx 

thanks for reporting the issue. I fixed it by setting background: transparent !important; for the textarea - this is what Github and many other big sites are using so the text won't be shown as white when the Grammarly extension is installed.
